# Estiamação Neuronal

Estamos usando a função de ativação $\varphi(\cdot)$, perda $g$ (um fator multiplicativo) a cada instante, um grafo completo ponderado e orientado $w$ com $n$ vértices, sendo $w_{i \rightarrow j}=1, \ \ i,j = 1,2,\cdots,n$.

Usamos um grafo completo unitário para podermos ter resultados comparáveis com os encontrados por Diogo, que também definiu $g=0.8$.
$$
\varphi(v) = \frac{a}{1+ \exp(-bv+c)}
$$
Isso, é, uma sigmoide genérica. Convencionamos $a=1$ e queremos que essa $\varphi$ satisfaça $\varphi(0) = 0.05$ (probabilidade de disparo espontâneo):
$$
\begin{aligned}
\varphi(0) &= \frac{a}{1+ \exp(-b0+c)} \\
&= \frac{1}{1+ \exp(c)} \\
\end{aligned} 
$$

$$
\frac{1}{1+ \exp(c)} = 0.05 \Rightarrow (c) = \ln(19) \approx 2.94444
$$



e $\varphi(u)=0.7$ (Ponto de inflexão). Surge, portanto, a seguinte relação:
$$
\begin{aligned}
0.7 &= \frac{\partial^2}{\partial v^2} \left( \frac{a}{1 + e^{-b v + c}} \right) \Bigg{|}_{v=u}  \\
&= a \left( \frac{2 b^2 e^{2c - 2b v}}{(e^{c - b v} + 1)^3}
- \frac{b^2 e^{c - b v}}{(e^{c - b v} + 1)^2} \right) \Bigg{|}_{v=u} \\
&= a \left( \frac{2 b^2 e^{2c - 2b u}}{(e^{c - b u} + 1)^3}
- \frac{b^2 e^{c - b u}}{(e^{c - b u} + 1)^2} \right) \\
\end{aligned}
$$
Basta resolver a equação restante.
$$
\begin{aligned}
0.7 &= a \left( \frac{2 b^2 e^{2c - 2b u}}{(e^{c - b u} + 1)^3}
- \frac{b^2 e^{c - b u}}{(e^{c - b u} + 1)^2} \right) \\

&= \frac{ab^2}{(e^{c - b u} + 1)^2} \left( \frac{2  e^{2c - 2b u}}{(e^{c - b u} + 1)}
-e^{c - b u} \right) \\

&= \frac{ab^2}{(e^{c - b u} + 1)^2} \left( \frac{2  e^{2c - 2b u}}{(e^{c - b u} + 1)}
- \frac{ (e^{c - b u})(e^{c - b u} + 1) }{(e^{c - b u} + 1)} \right) \\

&= \frac{ab^2}{(e^{c - b u} + 1)^2} \left( \frac{2  e^{2c - 2b u}}{(e^{c - b u} + 1)}
- \frac{e^{2c - 2b u} + e^{c - b u} }{(e^{c - b u} + 1)} \right) \\

&= \frac{ab^2}{(e^{c - b u} + 1)^2} \left( \frac{ e^{2c - 2b u} + e^{c - b u}}{(e^{c - b u} + 1)} \right) \\

&= \frac{ab^2}{(e^{c - b u} + 1)^2}    \left( \frac{ (e^{c - b u}) (e^{c - b u} +1)}{(e^{c - b u} + 1)} \right) \\

&= \frac{ab^2(e^{c - b u})}{(e^{c - b u} + 1)^2}\\

\end{aligned}
$$
Note que não é possível isolar $b$ algebricamente, pois trata-se de uma equação transcendental. Todavia, podemos inserir os valores determinados anteriormente ($a=1, c=\ln(19)$)
$$
\begin{aligned}
0.7 &= \frac{b^2(e^{\ln(19) - b u})}{(e^{\ln(19) - b u} + 1)^2}\\
&= \frac{b^2(19 e^{ - b u})}{(19e^{- b u} + 1)^2}\\

\end{aligned}
$$
Abaixo, uma tabela com valores de $u$ e seus respectivos valores para $b$:

| \(u\) |  \(b_1\)  | \(b_2\) |
| ----: | :-------: | :-----: |
|  0.0  |  -3.84 | 3.84 |
|  0.1  |  -4.78 | 3.32 |
|  0.2  | -9.57, -10.73 | 2.97 |
|  0.3  |  2.72 | 34.63 |
|  0.4  |  2.52 | 24.17 |
|  0.5  |  2.37 | 18.2  |
|  0.6  |  2.24 | 14.38 |
|  0.7  |  2.13 | 11.74 |
|  0.8  |  2.04 | 9.82  |
|  0.9  |  1.97 | 8.37  |
|  1.0  |  1.90 | 7.23  |
|  2.0  | 1.73  | 2.33  |
|  3.0  |   —   |   —   |
|  4.0  |   —   |   —   |